# Generated by Django 4.0.4 on 2022-07-31 13:12
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="news.category",
            ),
            preserve_default=False,
        ),
    ]
